name: Python package

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  module_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build application
        run: docker-compose build app
        env:
          PYTHON_VERSION: "3.12"
          DJANGO_VERSION: "4.2"
      - name: Show installed dependencies
        run: docker-compose run app pip list
      - name: Build test
        run: docker-compose run tox
      - name: Show docker process
        run: docker ps
        if: always()